import Link from 'next/link';
import { ArrowRight, Check, MessageCircle, MousePointer2, PenLine, ShieldCheck } from 'lucide-react';
import { Button, Logo } from '@my-view/ui';
export default function Home() {
  return <div className="max-w-6xl mx-auto px-6 md:px-12">
    <header className="py-7 flex justify-between items-center border-b border-stone-200"><Logo /><nav className="flex gap-4 items-center"><Link className="text-sm text-stone-600" href="/profile">My preferences</Link><Button asChild size="sm"><Link href="/sign-in">Sign in<ArrowRight size={14}/></Link></Button></nav></header>
    <main className="py-20 md:py-28 grid md:grid-cols-2 gap-16 items-center">
      <section><p className="eyebrow">A little help joining in</p><h1 className="text-5xl md:text-6xl font-semibold leading-[1.08] tracking-tight mt-5">Your perspective<br/>belongs in<br/><span className="text-teal-800">the conversation.</span></h1><p className="text-lg leading-8 text-stone-500 mt-7 max-w-md">Sometimes you know what you think, but finding the words takes a little longer. My View helps you get started, right alongside Facebook.</p><Button asChild className="mt-8"><Link href="/onboarding">Make it your own<ArrowRight size={16}/></Link></Button><p className="flex gap-2 text-xs text-stone-500 mt-5"><ShieldCheck size={16}/>Your words. Your choice to publish.</p></section>
      <section className="rounded-3xl border border-stone-200 bg-white shadow-xl shadow-stone-200/40 p-6 md:p-8 rotate-1"><div className="flex items-center justify-between"><Logo /><span className="text-xs text-teal-700 bg-teal-50 rounded-full px-3 py-1">Alongside Facebook</span></div><div className="mt-7 bg-stone-50 rounded-2xl p-5"><p className="eyebrow">The conversation</p><p className="text-sm leading-7 mt-2 text-stone-600">“What could we do to make it easier for people to get around our town?”</p></div><p className="eyebrow mt-6">Your reply · Written by you</p><div className="mt-3 border border-stone-200 rounded-xl p-5 text-sm leading-7">I’d love to hear more about the options for local buses. Has anyone looked at what would make the biggest difference?</div><div className="bg-teal-800 text-white text-sm font-semibold rounded-xl mt-5 p-4 flex justify-center gap-2"><PenLine size={18}/>Edit, then insert into Facebook</div><p className="text-xs leading-5 mt-4 text-stone-500 flex gap-2"><Check size={15}/>You review and click Comment yourself.</p></section>
    </main>
    <section className="grid md:grid-cols-3 gap-6 pb-20">{[{ Icon: MousePointer2, title: 'Choose a conversation', body: 'Open My View on a post, or highlight its text and use the right-click menu.' },{ Icon: PenLine, title: 'Make the reply yours', body: 'Write a reply directly, or edit a suggested starting point until it sounds like you.' },{ Icon: MessageCircle, title: 'Join in when you’re ready', body: 'Insert or copy your reply. Review it in Facebook and decide whether to publish.' }].map(({ Icon,title,body },i) => <div className="border-t border-stone-200 pt-6" key={title}><Icon size={22} className="text-teal-800"/><h2 className="font-semibold mt-4">{i+1}. {title}</h2><p className="text-sm leading-6 mt-2 text-stone-500">{body}</p></div>)}</section>
    <footer className="py-6 border-t border-stone-200 flex justify-between text-xs text-stone-500"><span>My View · Early prototype</span><Link href="/privacy">How your information is used</Link></footer>
  </div>;
}
